"""Initial schema

Revision ID: 7e613dac1630
Revises: 
Create Date: 2026-08-20 09:47:40.247021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e613dac1630'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ddl_case_id', sa.String(length=64), nullable=True),
    sa.Column('filing_month', sa.Integer(), nullable=True),
    sa.Column('filing_day_of_week', sa.Integer(), nullable=True),
    sa.Column('filing_quarter', sa.Integer(), nullable=True),
    sa.Column('type_name', sa.String(length=128), nullable=False),
    sa.Column('case_type_str', sa.String(length=128), nullable=True),
    sa.Column('case_category', sa.String(length=64), nullable=True),
    sa.Column('is_criminal_code', sa.Integer(), nullable=True),
    sa.Column('statutory_act_count', sa.Integer(), nullable=True),
    sa.Column('ipc_section_count', sa.Integer(), nullable=True),
    sa.Column('bailable_ipc_flag', sa.String(length=32), nullable=True),
    sa.Column('primary_act_id', sa.String(length=128), nullable=True),
    sa.Column('female_defendant_clean', sa.String(length=32), nullable=True),
    sa.Column('female_petitioner_clean', sa.String(length=32), nullable=True),
    sa.Column('female_adv_def_clean', sa.String(length=32), nullable=True),
    sa.Column('female_adv_pet_clean', sa.String(length=32), nullable=True),
    sa.Column('state_code', sa.String(length=32), nullable=False),
    sa.Column('dist_code', sa.String(length=32), nullable=False),
    sa.Column('court_no', sa.String(length=32), nullable=False),
    sa.Column('state_str', sa.String(length=128), nullable=True),
    sa.Column('district_str', sa.String(length=128), nullable=True),
    sa.Column('court_str', sa.String(length=256), nullable=True),
    sa.Column('ddl_filing_judge_id', sa.String(length=64), nullable=True),
    sa.Column('judge_position_clean', sa.String(length=128), nullable=True),
    sa.Column('judge_gender', sa.String(length=32), nullable=True),
    sa.Column('judge_tenure_days', sa.Float(), nullable=True),
    sa.Column('court_prior_delay_rate', sa.Float(), nullable=True),
    sa.Column('court_prior_avg_duration', sa.Float(), nullable=True),
    sa.Column('court_prior_active_backlog', sa.Float(), nullable=True),
    sa.Column('casetype_prior_delay_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_court_no'), 'cases', ['court_no'], unique=False)
    op.create_index(op.f('ix_cases_created_at'), 'cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_cases_ddl_case_id'), 'cases', ['ddl_case_id'], unique=False)
    op.create_index(op.f('ix_cases_ddl_filing_judge_id'), 'cases', ['ddl_filing_judge_id'], unique=False)
    op.create_index(op.f('ix_cases_dist_code'), 'cases', ['dist_code'], unique=False)
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_index(op.f('ix_cases_state_code'), 'cases', ['state_code'], unique=False)
    op.create_index('ix_cases_state_dist_court', 'cases', ['state_code', 'dist_code', 'court_no'], unique=False)
    op.create_index(op.f('ix_cases_type_name'), 'cases', ['type_name'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('prediction_type', sa.String(length=32), nullable=False),
    sa.Column('raw_probability', sa.Float(), nullable=True),
    sa.Column('calibrated_probability', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_band', sa.String(length=32), nullable=True),
    sa.Column('predicted_duration_days', sa.Float(), nullable=True),
    sa.Column('limitations_flag', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_case_id'), 'predictions', ['case_id'], unique=False)
    op.create_index(op.f('ix_predictions_created_at'), 'predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_risk_band'), 'predictions', ['risk_band'], unique=False)
    op.create_index(op.f('ix_predictions_risk_score'), 'predictions', ['risk_score'], unique=False)
    op.create_table('explanations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prediction_id', sa.String(length=36), nullable=False),
    sa.Column('feature_name', sa.String(length=128), nullable=False),
    sa.Column('parent_feature', sa.String(length=128), nullable=False),
    sa.Column('feature_group', sa.String(length=64), nullable=False),
    sa.Column('human_readable_description', sa.Text(), nullable=True),
    sa.Column('contribution', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('feature_value', sa.String(length=256), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explanations_id'), 'explanations', ['id'], unique=False)
    op.create_index(op.f('ix_explanations_prediction_id'), 'explanations', ['prediction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_explanations_prediction_id'), table_name='explanations')
    op.drop_index(op.f('ix_explanations_id'), table_name='explanations')
    op.drop_table('explanations')
    op.drop_index(op.f('ix_predictions_risk_score'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_risk_band'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_created_at'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_case_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_cases_type_name'), table_name='cases')
    op.drop_index('ix_cases_state_dist_court', table_name='cases')
    op.drop_index(op.f('ix_cases_state_code'), table_name='cases')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_dist_code'), table_name='cases')
    op.drop_index(op.f('ix_cases_ddl_filing_judge_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_ddl_case_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_at'), table_name='cases')
    op.drop_index(op.f('ix_cases_court_no'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
